# Generated by Django 4.2.4 on 2023-12-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='browser',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='ip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='os',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='browser',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='ip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='os',
            field=models.TextField(blank=True, null=True),
        ),
    ]
