# Generated by Django 4.2.4 on 2023-12-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_hiringrecord_birth_date_hiringrecord_fb_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringrecord',
            name='fb_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook Profile URL'),
        ),
        migrations.AlterField(
            model_name='hiringrecord',
            name='insta_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram Profile URL'),
        ),
        migrations.AlterField(
            model_name='hiringrecord',
            name='last_education',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Education'),
        ),
        migrations.AlterField(
            model_name='hiringrecord',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LinkedIn Profile URL'),
        ),
        migrations.AlterField(
            model_name='hiringrecord',
            name='tiktok_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TikTok Profile URL'),
        ),
    ]
